-------------------------------------------------------------------------------
Test set: enterprise.framework.AuthTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 32.122 s <<< FAILURE! - in enterprise.framework.AuthTest
updateUserToken(enterprise.framework.AuthTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/boot/autoconfigure/session/RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.8:6382

DateTest(enterprise.framework.AuthTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource [org/springframework/boot/autoconfigure/session/RedisSessionConfiguration$SpringBootRedisHttpSessionConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: org.springframework.data.redis.connection.PoolException: Could not get a resource from the pool; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 172.17.0.8:6382
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.8:6382

